steps:
- task: DotNetCoreCLI@2
    displayName: Restore
    inputs:
      command: restore
      projects: '$(solution)'

- task: DotNetCoreCLI@2
    displayName: Build
    inputs:
      projects: '$(solution)'
      arguments: '--configuration $(BuildConfiguration)'

- task: DotNetCoreCLI@2
    displayName: Test
    inputs:
      command: test
      projects: '$(solution)'
      arguments: '--configuration $(BuildConfiguration)'

- task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)'
      ArtifactName: 'artifacts'
      publishLocation: 'Container'