trigger:
  - master
    
pool:
  vmImage: 'windows-latest'
    
variables:
  solution: 'src/ArmyDocs/ArmyDocs.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Debug'

steps:
  - template: BuildSolution.yml